In [3]:
import matplotlib.pyplot as plt
import numpy as np
import networkx as nx
import pandas
from io import StringIO
import sympy
import scipy
from sklearn.preprocessing import normalize
from pathlib import Path

In [4]:
# Funcion para correr .cpp

TP = "../src/main"
TEST_DIR = "../tests/"

def run_test(test_name: str, niter: int, eps: float): 
    !{TP} {TEST_DIR + test_name} {niter} {eps}

def read_result_autovalores(test_result: str):
    return pandas.read_csv(TEST_DIR + test_result + '_autovalores.out', names=["autovalores"])

def read_result_autovectores(test_result: str):
    return pandas.read_csv(TEST_DIR + test_result + '_autovectores.out' , names=["autovectores"])

### 1. Tests metodo de la potencia

In [5]:
# CASO SIMETRICO
A = np.array([
  [ 7,  2,  -3],
  [ 2,  2,  -2],
  [-3, -2,  -2]
])

# GUARDO TXT
np.savetxt("../tests/simetrico.txt", A, delimiter=' ')

# CORRO METODO
run_test("simetrico.txt", 100000, 1e-20)

# CARGO AUTOVALORES Y AUTOVECTORES
l = np.loadtxt("../tests/simetrico.txt_autovalores.out", dtype='f', delimiter=' ')
v = np.loadtxt("../tests/simetrico.txt_autovectores.out", dtype='f', delimiter=' ', usecols=range(3))

print(l)
print(v)


print(A @ v[:, 0])
print(l[0] * v[:,0])

for i in range(len(A)):
    print(i)
    print(np.allclose(A @ v[:, i], l[i] * v[:,i], 1e-6))


Corriendo el programa...
autovalor: 0
frene en iteracion: 100000
valor = 8.83835
autovalor: 1
frene en iteracion: 100000
valor = -3.28495
autovalor: 2
frene en iteracion: 100000
valor = 1.4466
[ 8.83835   -3.2849522  1.446602 ]
[[ 0.88455707 -0.22057717 -0.41097993]
 [ 0.34915668 -0.27109465  0.89699346]
 [-0.30927074 -0.9369383  -0.16278271]]
[ 7.81802505  3.08596897 -2.73344308]
[ 7.818025  3.085969 -2.733443]
0
True
1
True
2
True


In [6]:
# CASO (A) * (A traspuesta)
AT = A @ A.T
TA = A.T @ A

# GUARDO TXT
np.savetxt("../tests/AT.txt", AT, delimiter=' ')
np.savetxt("../tests/TA.txt", TA, delimiter=' ')

# CORRO METODO
run_test("AT.txt", 100000, 1e-20)
run_test("TA.txt", 100000, 1e-20)

# CARGO AUTOVALORES Y AUTOVECTORES
l_AT = np.loadtxt("../tests/AT.txt_autovalores.out", dtype='f', delimiter=' ')
v_AT = np.loadtxt("../tests/AT.txt_autovectores.out", dtype='f', delimiter=' ', usecols=range(3))

l_TA = np.loadtxt("../tests/TA.txt_autovalores.out", dtype='f', delimiter=' ')
v_TA = np.loadtxt("../tests/TA.txt_autovectores.out", dtype='f', delimiter=' ', usecols=range(3))

print(l_AT)
print(l_TA)
print("Bingo :)" if np.allclose(l_AT,l_TA) else "Bongo :(")
print("Bingo :)" if np.allclose(v_AT,v_TA) else "Bongo :(")

Corriendo el programa...
autovalor: 0
frene en iteracion: 100000
valor = 78.1164
autovalor: 1
frene en iteracion: 100000
valor = 10.7909
autovalor: 2
frene en iteracion: 100000
valor = 2.09266
Corriendo el programa...
autovalor: 0
frene en iteracion: 100000
valor = 78.1164
autovalor: 1
frene en iteracion: 100000
valor = 10.7909
autovalor: 2
frene en iteracion: 100000
valor = 2.09266
[78.11643   10.79091    2.0926573]
[78.11643   10.79091    2.0926573]
Bingo :)
Bingo :)


### Ej 2 Juli

### PCA

In [7]:
paths = []
imgs = []
for path in sorted(list(Path('caras').rglob('*/*.pgm'))):
    paths.append(path)
    imgs.append(plt.imread(path)[::2,::2]/255)
X = np.stack(imgs)

In [ ]:
n = X.shape[0] # Cantidad de imagenes

X = X.reshape(n, -1) # X pasa a tener dimension n x (46 x 56)

X_centered = X - X.mean(0) # X.mean(0) devuelve un arreglo con la media de cada columna.

Mx = X_centered.T@X_centered/(n-1)  # Mx = Matriz de covarianza

# Calculo autovalores con numpy
# l, V = np.linalg.eigh(Mx)

# GUARDO TXT
np.savetxt("../tests/pca.txt", Mx, fmt='%.5f', delimiter=' ') # Trunca en 5 decimales (esta bien?)

# CORRO METODO
run_test("pca.txt", 10000, 1e-16)

# CARGO AUTOVALORES Y AUTOVECTORES
l = np.loadtxt("../tests/pca.txt_autovalores.out", dtype='f', delimiter=' ')
v = np.loadtxt("../tests/pca.txt_autovectores.out", dtype='f', delimiter=' ', usecols=range(3))

print(l)


### =======================================================================================

### 2DPCA

In [8]:
paths = []
imgs = []
for path in sorted(list(Path('caras').rglob('*/*.pgm'))):
    paths.append(path)
    imgs.append(plt.imread(path)[::2,::2]/255)
X = np.stack(imgs)

La variante 2DPCA 2 considera una imagen en su espacio original como una matriz A ∈ Ra×b
y le asocia un feature vector Y ∈ Ra, mediante la transformacion lineal Y = AX siendo
X ∈ Rb el vector que maximiza la dispersion de los features vectors obtenidos para todo el
conjunto de imagenes. Se puede ver que la eleccion  ́optima para el vector de proyeccion X
se corresponde con el autovector de maximo autovalor de la denominada image covariance
matrix

In [9]:
print(f"Tengo {X.shape[0]} imagenes de tamano {X.shape[1]}x{X.shape[2]}")
# A es la imagen
imgs = X

n = imgs.shape[0] # Cantidad de imagenes

A_prom = np.zeros(shape=(imgs.shape[1], imgs.shape[2]))

for i in range (n):
    A_prom += imgs[i]

A_prom /= n


# G = image covariance matrix (quiero calcularle autovalores y autovectores)
sum = 0
for j in range (n): 
    sum += (np.transpose(imgs[j] - A_prom)) @ (imgs[j] - A_prom)
G = (1/n) * sum

# GUARDO TXT
np.savetxt("../tests/2dpca_g.txt", G, delimiter=' ')

# CORRO METODO
run_test("2dpca_g.txt", 100000, 1e-20)

# CARGO AUTOVALORES Y AUTOVECTORES
l = np.loadtxt("../tests/2dpca_g.txt_autovalores.out", dtype='f', delimiter=' ')
v = np.loadtxt("../tests/2dpca_g.txt_autovectores.out", dtype='f', delimiter=' ', usecols=range(3))

print(l)

# V = matriz de feature vectors
# U = base de autovectores ortonormales de G
# V = imgs[0] @ U


# Quiero computar los Zi = (AiX1, AiX2, ..., AiXk) de cada imagen
# donde cada AiXk representa el k-esimo feature vector de la imagen Ai



Tengo 410 imagenes de tamano 56x46
Corriendo el programa...
autovalor: 0
frene en iteracion: 100000
valor = 24.336
autovalor: 1
frene en iteracion: 100000
valor = 9.22444
autovalor: 2
frene en iteracion: 100000
valor = 5.51641
autovalor: 3
frene en iteracion: 100000
valor = 3.58365
autovalor: 4
frene en iteracion: 100000
valor = 2.56006
autovalor: 5
frene en iteracion: 100000
valor = 2.27905
autovalor: 6
frene en iteracion: 100000
valor = 1.89894
autovalor: 7
frene en iteracion: 100000
valor = 1.51019
autovalor: 8
frene en iteracion: 100000
valor = 1.22432
autovalor: 9
frene en iteracion: 100000
valor = 0.912122
autovalor: 10
frene en iteracion: 100000
valor = 0.817493
autovalor: 11
frene en iteracion: 100000
valor = 0.69328
autovalor: 12
frene en iteracion: 100000
valor = 0.598931
autovalor: 13
frene en iteracion: 100000
valor = 0.540598
autovalor: 14
frene en iteracion: 100000
valor = 0.500033
autovalor: 15
frene en iteracion: 100000
valor = 0.418575
autovalor: 16
frene en iteracion:

In [10]:
# Comparo con numpy y los autovalores dan bien
w, v = np.linalg.eig(G)
print(w)

[24.33601316  9.22444343  5.51640648  3.58364936  2.56005771  2.27904766
  1.89893743  1.51019041  1.22432041  0.91212187  0.81749301  0.69327971
  0.59893117  0.54059843  0.50003312  0.41857472  0.38475508  0.35087807
  0.32296028  0.29836419  0.28924235  0.28277881  0.25627299  0.25524637
  0.23614001  0.22612349  0.21252217  0.20014409  0.19668569  0.18462956
  0.15993273  0.14576382  0.1416123   0.12739465  0.11138012  0.10263379
  0.09554524  0.09226445  0.08513965  0.07823591  0.0761303   0.07118081
  0.06411526  0.06786507  0.06629719  0.06661741]


### Ej 3