In [1]:
import matplotlib.pyplot as plt
import numpy as np
import networkx as nx
import pandas
from io import StringIO
import sympy
import scipy
from sklearn.preprocessing import normalize
from pathlib import Path

In [2]:
# Funcion para correr .cpp

TP = "../src/main"
TEST_DIR = "../tests/"

def run_test(test_name: str, niter: int, eps: float): 
    !{TP} {TEST_DIR + test_name} {niter} {eps}

def run_test_pca(test_name: str, niter: int, eps: float, cant: int): 
    !{TP} {TEST_DIR + test_name} {niter} {eps} {cant}

def read_result_autovalores(test_result: str):
    return pandas.read_csv(TEST_DIR + test_result + '_autovalores.out', names=["autovalores"])

def read_result_autovectores(test_result: str):
    return pandas.read_csv(TEST_DIR + test_result + '_autovectores.out' , names=["autovectores"])

### 1. Tests metodo de la potencia

In [3]:
# CASO SIMETRICO
A = np.array([
  [ 7,  2,  -3],
  [ 2,  2,  -2],
  [-3, -2,  -2]
])

# GUARDO TXT
np.savetxt("../tests/simetrico.txt", A, delimiter=' ')

# CORRO METODO
run_test("simetrico.txt", 100000, 1e-21)

# CARGO AUTOVALORES Y AUTOVECTORES
l = np.loadtxt("../tests/simetrico.txt_autovalores.out", dtype='f', delimiter=' ')
v = np.loadtxt("../tests/simetrico.txt_autovectores.out", dtype='f', delimiter=' ', usecols=range(3))

print(l)
print(v)


print(A @ v[:, 0])
print(l[0] * v[:,0])

for i in range(len(A)):
    print(i)
    print(np.allclose(A @ v[:, i], l[i] * v[:,i], 1e-6))


Corriendo el programa...
autovalor: 0
frene en iteracion: 100000
valor = 8.83835
autovalor: 1
frene en iteracion: 100000
valor = -3.28495
autovalor: 2
frene en iteracion: 100000
valor = 1.4466
[ 8.83835   -3.2849522  1.446602 ]
[[ 0.88455707 -0.22057717 -0.41097993]
 [ 0.34915668 -0.27109465  0.89699346]
 [-0.30927074 -0.9369383  -0.16278271]]
[ 7.81802505  3.08596897 -2.73344308]
[ 7.818025  3.085969 -2.733443]
0
True
1
True
2
True


In [4]:
# CASO (A) * (A traspuesta)
AT = A @ A.T
TA = A.T @ A

# GUARDO TXT
np.savetxt("../tests/AT.txt", AT, delimiter=' ')
np.savetxt("../tests/TA.txt", TA, delimiter=' ')

# CORRO METODO
run_test("AT.txt", 100000, 1e-21)
run_test("TA.txt", 100000, 1e-21)

# CARGO AUTOVALORES Y AUTOVECTORES
l_AT = np.loadtxt("../tests/AT.txt_autovalores.out", dtype='f', delimiter=' ')
v_AT = np.loadtxt("../tests/AT.txt_autovectores.out", dtype='f', delimiter=' ', usecols=range(3))

l_TA = np.loadtxt("../tests/TA.txt_autovalores.out", dtype='f', delimiter=' ')
v_TA = np.loadtxt("../tests/TA.txt_autovectores.out", dtype='f', delimiter=' ', usecols=range(3))

print(l_AT)
print(l_TA)
print("Bingo :)" if np.allclose(l_AT,l_TA) else "Bongo :(")
print("Bingo :)" if np.allclose(v_AT,v_TA) else "Bongo :(")

Corriendo el programa...
autovalor: 0
frene en iteracion: 100000
valor = 78.1164
autovalor: 1
frene en iteracion: 100000
valor = 10.7909
autovalor: 2
frene en iteracion: 100000
valor = 2.09266
Corriendo el programa...
autovalor: 0
frene en iteracion: 100000
valor = 78.1164
autovalor: 1
frene en iteracion: 100000
valor = 10.7909
autovalor: 2
frene en iteracion: 100000
valor = 2.09266
[78.11643   10.79091    2.0926573]
[78.11643   10.79091    2.0926573]
Bingo :)
Bingo :)


### Ej 2 Juli

### PCA

In [5]:
paths = []
imgs = []
for path in sorted(list(Path('caras').rglob('*/*.pgm'))):
    paths.append(path)
    imgs.append(plt.imread(path)[::2,::2]/255)
X = np.stack(imgs)

In [7]:
n = X.shape[0] # Cantidad de imagenes

X = X.reshape(n, -1) # X pasa a tener dimension n x (46 x 56)

X_centered = X - X.mean(0) # X.mean(0) devuelve un arreglo con la media de cada columna.

Mx = X_centered.T@X_centered/(n-1)  # Mx = Matriz de covarianza

# Calculo autovalores con numpy
# l, V = np.linalg.eigh(Mx)

# GUARDO TXT
np.savetxt("../tests/pca.txt", Mx, fmt='%.5f', delimiter=' ') # Trunca en 5 decimales (esta bien?)

# CORRO METODO
#run_test("pca.txt", 10000, 1e-5)
run_test_pca("pca.txt", 10000, 1e-16, 409)

# CARGO AUTOVALORES Y AUTOVECTORES
#l = np.loadtxt("../tests/pca.txt_autovalores.out", dtype='f', delimiter=' ')
#v = np.loadtxt("../tests/pca.txt_autovectores.out", dtype='f', delimiter=' ', usecols=range(3))

#print(l)


Corriendo el programa...
autovalor: 0
frene en iteracion: 46
valor = 10.9606
autovalor: 1
frene en iteracion: 27
valor = 7.93519
autovalor: 2
frene en iteracion: 56
valor = 4.242
autovalor: 3
frene en iteracion: 147
valor = 3.44357
autovalor: 4
frene en iteracion: 60
valor = 3.0758
autovalor: 5
frene en iteracion: 63
valor = 2.16801
autovalor: 6
frene en iteracion: 118
valor = 1.60432
autovalor: 7
frene en iteracion: 103
valor = 1.41619
autovalor: 8
frene en iteracion: 176
valor = 1.22675
autovalor: 9
frene en iteracion: 74
valor = 1.11281
autovalor: 10
frene en iteracion: 187
valor = 0.917016
autovalor: 11
frene en iteracion: 100
valor = 0.843244
autovalor: 12
frene en iteracion: 197
valor = 0.722839
autovalor: 13
frene en iteracion: 187
valor = 0.654554
autovalor: 14
frene en iteracion: 232
valor = 0.604213
autovalor: 15
frene en iteracion: 396
valor = 0.569328
autovalor: 16
frene en iteracion: 322
valor = 0.547681
autovalor: 17
frene en iteracion: 119
valor = 0.524462
autovalor: 18


### =======================================================================================

### 2DPCA

In [ ]:
paths = []
imgs = []
for path in sorted(list(Path('caras').rglob('*/*.pgm'))):
    paths.append(path)
    imgs.append(plt.imread(path)[::2,::2]/255)
X = np.stack(imgs)

La variante 2DPCA 2 considera una imagen en su espacio original como una matriz A ∈ Ra×b
y le asocia un feature vector Y ∈ Ra, mediante la transformacion lineal Y = AX siendo
X ∈ Rb el vector que maximiza la dispersion de los features vectors obtenidos para todo el
conjunto de imagenes. Se puede ver que la eleccion  ́optima para el vector de proyeccion X
se corresponde con el autovector de maximo autovalor de la denominada image covariance
matrix

In [ ]:
print(f"Tengo {X.shape[0]} imagenes de tamano {X.shape[1]}x{X.shape[2]}")
# A es la imagen
imgs = X

n = imgs.shape[0] # Cantidad de imagenes

A_prom = np.zeros(shape=(imgs.shape[1], imgs.shape[2]))

for i in range (n):
    A_prom += imgs[i]

A_prom /= n


# G = image covariance matrix (quiero calcularle autovalores y autovectores)
sum = 0
for j in range (n): 
    sum += (np.transpose(imgs[j] - A_prom)) @ (imgs[j] - A_prom)
G = (1/n) * sum

# GUARDO TXT
np.savetxt("../tests/2dpca_g.txt", G, delimiter=' ')

# CORRO METODO
run_test("2dpca_g.txt", 100000, 1e-21)

# CARGO AUTOVALORES Y AUTOVECTORES
l = np.loadtxt("../tests/2dpca_g.txt_autovalores.out", dtype='f', delimiter=' ')
v = np.loadtxt("../tests/2dpca_g.txt_autovectores.out", dtype='f', delimiter=' ', usecols=range(3))

print(l)

# V = matriz de feature vectors
# U = base de autovectores ortonormales de G
# V = imgs[0] @ U


# Quiero computar los Zi = (AiX1, AiX2, ..., AiXk) de cada imagen
# donde cada AiXk representa el k-esimo feature vector de la imagen Ai



In [ ]:
# Comparo con numpy y los autovalores dan bien
w, v = np.linalg.eig(G)
print(w)

### Ej 3